version: '2'

services:
  mongo:
    container_name: mongo-vril
    image: mongo:3.6.9-stretch
    ports:
      - "5002:27017"
    volumes:
      - /data/db-dev

  redis:
    container_name: redis-vril
    image: redis:5.0.2-stretch
    ports:
      - "5003:6379"
    volumes:
      - /data/cc-dev

  swagger:
    container_name: swagger-vril-dev
    image: swaggerapi/swagger-ui
    ports:
      - "5001:8080"
    environment:
      - API_URL=http://generator.swagger.io/api/swagger.json