version: '2'

services:
  mongo:
    container_name: mongo-vril-dev
    image: mongo:3.6.6-jessie
    ports:
      - "5002:27017"
    volumes:
      - /data/db-dev

  swagger:
    container_name: swagger-vril-dev
    image: swaggerapi/swagger-ui
    ports:
      - "5001:8080"
    environment:
      - API_URL=http://generator.swagger.io/api/swagger.json