version: '2'

services:
  api-debug:
    build: .
    command: "npm run prod"
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    links:
      - mongo

  mongo:
    container_name: mongo-vril-prod
    image: mongo:3.6.9-stretch
    ports:
      - '5002:27017'
    volumes:
      - /data/db-prod

  swagger:
    container_name: swagger-vril-prod
    image: swaggerapi/swagger-ui
    ports:
      - "5001:8080"
    environment:
      - API_URL=http://generator.swagger.io/api/swagger.json